### ISSUE TITLE
Add stats

### ISSUE THREAD

**Issue by dclement8** [muonium/admin-panel#6]
We can show global stats like : 
- number of accounts
- number of paid plans
- total size
- total stored size

**Comment by Super-Baleine** [comment]
We also want to check the free storage space remaining on the server.

http://php.net/manual/en/function.disk-free-space.php

The path we want to check is `nova`. the relative path of `nova` is located in index.php in a constant.

**Comment by Super-Baleine** [comment]
@dclement8 what do you mean by "total stored size"? you mean what I meant just above or you mean the stored size of a user?
